name: genezio workflow
on:
  push:
    branches:
      - main

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: Genez-io/genezio-github-action@v2
        with:
          token: ${{ secrets.GENEZIO_TOKEN }}
      - name: Build frontend
        working-directory: ./client
        run: npm install && npm run build
        env:
          CI: false
      - name: Deploy frontend
        working-directory: ./
        run: genezio deploy
        env:
          CI: false
